### PR TITLE
Return HTML with http_api_handler

### PR DESCRIPTION
**Pull request by imihajlow**
REST is good, but generating HTML pages on-the-fly is also good and useful.
Returning a string from the get/post/put/delete methods sends an HTML content-type.

### CODE REVIEW

**Comment by fadushin** [comment]
Nice, let's add a test for this, as well.

**Comment by imihajlow** [comment]
@fadushin merge pls?

**Review by fadushin — APPROVED** [review]
+1

**Comment by fadushin** [comment]
@imihajlow I'd like to change the return semantics of the API handler, so that by default the handler will  return an object that can be translated to JSON, unless the return type is a tuple, in which case the first element of the tuple contains the content type (as a string), and the second contains the data.

This makes the interface cleaner for the target use-case (JSON API), but allows implementors to define their own return types.  I find it makes it easier to handle all JSON types (dicts, lists, ints, floats, bools, and strings), whereas when a handler returns string, it always is interpreted as HTML.

It does mean you will need to change your code to adapt to this semantic change.

**Comment by imihajlow** [comment]
Hi @fadushin,
Thanks for notifying, but I don't use micropython in my project anymore due to an unavoidable mbedtls/lwip bug. However, this sounds like a good change.

**Pull request merged**
